server:
  port: 8889
  servlet:
    context-path: /redbag
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/redbag?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true